spring.application.name=tatra-share

spring.datasource.url=jdbc:postgresql://localhost:15432/share_db
spring.datasource.username=share_user
spring.datasource.password=share_pass
spring.datasource.driver-class-name=org.postgresql.Driver