-- PostgreSQL init script for manual testing based on the provided diagram
-- Tables: "user", "group", group_user, transaction, transaction_payed_for

BEGIN;

-- Drop in FK-safe order
DROP TABLE IF EXISTS transaction_payed_for CASCADE;
DROP TABLE IF EXISTS transaction CASCADE;
DROP TABLE IF EXISTS group_user CASCADE;
DROP TABLE IF EXISTS "group" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    iban VARCHAR(34) NOT NULL UNIQUE
);

CREATE TABLE "group" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL
);

CREATE TABLE group_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT fk_group_user_user
        FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_user_group
        FOREIGN KEY (group_id) REFERENCES "group"(id) ON DELETE CASCADE,
    CONSTRAINT uq_group_user UNIQUE (user_id, group_id)
);

CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payed_user_id BIGINT NOT NULL,
    amount BIGINT NOT NULL CHECK (amount > 0),
    name VARCHAR(120) NOT NULL,
    description TEXT,
    group_id BIGINT NOT NULL,
    CONSTRAINT fk_transaction_payed_user
        FOREIGN KEY (payed_user_id) REFERENCES "user"(id) ON DELETE RESTRICT,
    CONSTRAINT fk_transaction_group
        FOREIGN KEY (group_id) REFERENCES "group"(id) ON DELETE CASCADE
);

CREATE TABLE transaction_payed_for (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_transaction_payed_for_transaction
        FOREIGN KEY (transaction_id) REFERENCES transaction(id) ON DELETE CASCADE,
    CONSTRAINT fk_transaction_payed_for_user
        FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT uq_transaction_payed_for UNIQUE (transaction_id, user_id)
);

-- Users
INSERT INTO "user" (id, full_name, iban) VALUES
    (1, 'Puhlia Boss', 'SK5211000000000101010101'),
    (2, 'Axel the Axolotl', 'SK3111000000001111222233'),
    (3, 'Leonid Kurtishov', 'SK4711000000004444555566'),
    (4, 'Anna Koval', 'SK1811000000007777888899'),
    (5, 'Petro Novak', 'SK2911000000001212121212'),
    (6, 'Sofia Melnyk', 'SK6311000000009898989898'),
    (7, 'Roman Hric', 'SK7411000000005656565656'),
    (8, 'Nina Varga', 'SK8511000000003434343434');

-- Groups
INSERT INTO "group" (id, name) VALUES
    (1, 'PLUSH FAMILY'),
    (2, 'Trip HackKosice'),
    (3, 'Office Lunch'),
    (4, 'Gym Buddies');

-- Group memberships
INSERT INTO group_user (user_id, group_id) VALUES
-- PLUSH FAMILY
(1,1),(2,1),(3,1),(4,1),

-- Trip HackKosice
(1,2),(2,2),(5,2),(6,2),

-- Office Lunch
(1,3),(3,3),(6,3),(7,3),

-- Gym Buddies
(2,4),(5,4),(7,4),(8,4);

-- Transactions
INSERT INTO transaction (id, payed_user_id, amount, name, description, group_id) VALUES
-- PLUSH FAMILY
(1, 1, 12000, 'Groceries', 'Weekly shopping', 1),
(2, 2, 6000, 'Pharmacy', 'Medicines', 1),
(3, 4, 10000, 'Utilities', 'Electricity + water', 1),

-- Trip HackKosice
(4, 1, 20000, 'Hotel', '2 nights stay', 2),
(5, 2, 7000, 'Fuel', 'Travel fuel', 2),
(6, 5, 9000, 'Dinner', 'Restaurant', 2),

-- Office Lunch
(7, 1, 4000, 'Lunch Monday', 'Team lunch', 3),
(8, 3, 3500, 'Lunch Wednesday', 'Midweek lunch', 3),
(9, 6, 5000, 'Lunch Friday', 'End week lunch', 3),

-- Gym Buddies
(10, 2, 4500, 'Gym Membership', 'Monthly fee', 4),
(11, 5, 3000, 'Protein Shake', 'Post workout', 4),
(12, 7, 2500, 'Supplements', 'Vitamins', 4);


-- Transaction splits (who owes)
INSERT INTO transaction_payed_for (transaction_id, user_id) VALUES

-- PLUSH FAMILY
(1,2),(1,3),(1,4),
(2,1),(2,3),(2,4),
(3,1),(3,2),(3,3),

-- Trip HackKosice
(4,2),(4,5),(4,6),
(5,1),(5,5),(5,6),
(6,1),(6,2),(6,6),

-- Office Lunch
(7,3),(7,6),(7,7),
(8,1),(8,6),(8,7),
(9,1),(9,3),(9,7),

-- Gym Buddies
(10,5),(10,7),(10,8),
(11,2),(11,7),(11,8),
(12,2),(12,5),(12,8);


-- Keep identity sequences aligned after explicit ids
SELECT setval(pg_get_serial_sequence('"user"', 'id'), COALESCE((SELECT MAX(id) FROM "user"), 1), true);
SELECT setval(pg_get_serial_sequence('"group"', 'id'), COALESCE((SELECT MAX(id) FROM "group"), 1), true);
SELECT setval(pg_get_serial_sequence('group_user', 'id'), COALESCE((SELECT MAX(id) FROM group_user), 1), true);
SELECT setval(pg_get_serial_sequence('transaction', 'id'), COALESCE((SELECT MAX(id) FROM transaction), 1), true);
SELECT setval(pg_get_serial_sequence('transaction_payed_for', 'id'), COALESCE((SELECT MAX(id) FROM transaction_payed_for), 1), true);

COMMIT;
