-- PostgreSQL init script for manual testing based on the provided diagram
-- Tables: "user", "group", group_user, transaction, transaction_payed_for

BEGIN;

-- Drop in FK-safe order
DROP TABLE IF EXISTS transaction_payed_for CASCADE;
DROP TABLE IF EXISTS transaction CASCADE;
DROP TABLE IF EXISTS group_user CASCADE;
DROP TABLE IF EXISTS "group" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    iban VARCHAR(34) NOT NULL UNIQUE
);

CREATE TABLE "group" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL
);

CREATE TABLE group_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT fk_group_user_user
        FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_user_group
        FOREIGN KEY (group_id) REFERENCES "group"(id) ON DELETE CASCADE,
    CONSTRAINT uq_group_user UNIQUE (user_id, group_id)
);

CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payed_user_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL CHECK ( amount > 0 ),
    name VARCHAR(120) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    group_id BIGINT NOT NULL,
    CONSTRAINT fk_transaction_payed_user
        FOREIGN KEY (payed_user_id) REFERENCES "user"(id) ON DELETE RESTRICT,
    CONSTRAINT fk_transaction_group
        FOREIGN KEY (group_id) REFERENCES "group"(id) ON DELETE CASCADE
);

CREATE TABLE transaction_payed_for (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_transaction_payed_for_transaction
        FOREIGN KEY (transaction_id) REFERENCES transaction(id) ON DELETE CASCADE,
    CONSTRAINT fk_transaction_payed_for_user
        FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT uq_transaction_payed_for UNIQUE (transaction_id, user_id)
);

-- Users
INSERT INTO "user" (id, full_name, iban) VALUES
    (1, 'Puhlia Boss', 'SK5211000000000101010101'),
    (2, 'Axel the Axolotl', 'SK3111000000001111222233'),
    (3, 'Leonid Kurtishov', 'SK4711000000004444555566'),
    (4, 'Anna Koval', 'SK1811000000007777888899'),
    (5, 'Petro Novak', 'SK2911000000001212121212'),
    (6, 'Sofia Melnyk', 'SK6311000000009898989898'),
    (7, 'Roman Hric', 'SK7411000000005656565656'),
    (8, 'Nina Varga', 'SK8511000000003434343434');

-- Groups
INSERT INTO "group" (id, name) VALUES
    (1, 'PLUSH FAMILY'),
    (2, 'Trip HackKosice'),
    (3, 'Office Lunch'),
    (4, 'Gym Buddies');

-- Group memberships
INSERT INTO group_user (user_id, group_id) VALUES
-- PLUSH FAMILY
(1,1),(2,1),(3,1),(4,1),

-- Trip HackKosice
(1,2),(2,2),(5,2),(6,2),

-- Office Lunch
(1,3),(3,3),(6,3),(7,3),

-- Gym Buddies
(2,4),(5,4),(7,4),(8,4);

-- Transactions
INSERT INTO transaction (id, payed_user_id, amount, name, description, created_at, group_id) VALUES
-- PLUSH FAMILY (4)
(1, 1, 48.60, 'Groceries', 'Weekly shopping', '2026-04-01 17:20:00', 1),
(2, 2, 12.90, 'Pharmacy', 'Medicines', '2026-04-04 11:05:00', 1),
(3, 4, 67.40, 'Utilities', 'Electricity + water', '2026-04-07 08:15:00', 1),
(4, 1, 19.80, 'Cleaning supplies', 'Home cleaning products', '2026-04-10 18:40:00', 1),

-- Trip HackKosice (2)
(5, 1, 186.00, 'Hotel', '2 nights stay', '2026-03-18 14:10:00', 2),
(6, 2, 42.50, 'Fuel', 'Travel fuel', '2026-03-19 09:35:00', 2),

-- Office Lunch (7)
(7, 1, 26.40, 'Lunch Monday', 'Team lunch', '2026-04-07 12:30:00', 3),
(8, 3, 31.20, 'Lunch Wednesday', 'Midweek lunch', '2026-04-09 12:45:00', 3),
(9, 6, 28.80, 'Lunch Friday', 'End week lunch', '2026-04-11 13:00:00', 3),
(10, 7, 24.50, 'Lunch Tuesday', 'Quick lunch menu', '2026-04-14 12:20:00', 3),
(11, 1, 33.60, 'Lunch Thursday', 'Burgers and drinks', '2026-04-16 13:10:00', 3),
(15, 3, 4.60, 'Debt return', 'Full debt return to current user in group Office Lunch', '2026-04-17 18:30:00', 3),
(16, 6, 54.00, 'Shared dinner', 'Dinner paid by Sofia', '2026-04-18 19:15:00', 3),

-- Gym Buddies (3)
(12, 2, 29.99, 'Gym Membership', 'Monthly fee contribution', '2026-02-28 18:00:00', 4),
(13, 5, 8.40, 'Protein Shake', 'Post workout drink', '2026-03-05 19:10:00', 4),
(14, 7, 17.90, 'Supplements', 'Vitamins', '2026-03-12 20:25:00', 4);

-- Transaction splits (beneficiaries)
INSERT INTO transaction_payed_for (transaction_id, user_id) VALUES

-- PLUSH FAMILY
-- 1: payer included
(1,1),(1,2),(1,3),(1,4),

-- 2: payer excluded
(2,1),(2,3),(2,4),

-- 3: payer included
(3,1),(3,2),(3,3),(3,4),

-- 4: payer included
(4,1),(4,3),

-- Trip HackKosice
-- 5: payer included
(5,1),(5,2),(5,5),(5,6),

-- 6: payer included
(6,1),(6,2),(6,5),(6,6),

-- Office Lunch
-- 7: payer included
(7,1),(7,3),(7,6),(7,7),

-- 8: payer included
(8,1),(8,3),(8,6),

-- 9: payer excluded
(9,1),(9,3),(9,7),

-- 10: payer included
(10,1),(10,6),(10,7),

-- 11: payer included
(11,1),(11,3),(11,6),(11,7),

-- 15: special repayment, single beneficiary
(15,1),

-- 16: payer included
(16,1),(16,3),(16,6),

-- Gym Buddies
-- 12: payer included
(12,2),(12,5),(12,7),(12,8),

-- 13: payer included
(13,2),(13,5),

-- 14: payer included
(14,2),(14,5),(14,7),(14,8);


-- Keep identity sequences aligned after explicit ids
SELECT setval(pg_get_serial_sequence('"user"', 'id'), COALESCE((SELECT MAX(id) FROM "user"), 1), true);
SELECT setval(pg_get_serial_sequence('"group"', 'id'), COALESCE((SELECT MAX(id) FROM "group"), 1), true);
SELECT setval(pg_get_serial_sequence('group_user', 'id'), COALESCE((SELECT MAX(id) FROM group_user), 1), true);
SELECT setval(pg_get_serial_sequence('transaction', 'id'), COALESCE((SELECT MAX(id) FROM transaction), 1), true);
SELECT setval(pg_get_serial_sequence('transaction_payed_for', 'id'), COALESCE((SELECT MAX(id) FROM transaction_payed_for), 1), true);

COMMIT;
